name: 'notion-to-jekyll - Publish Jekyll drafts and posts via Notion'
description: 'A tool to manage Jekyll drafts and posts (including assets) via Notion '
branding:
  icon: edit-3
  color: gray-dark
inputs:
  notion-token:
    description: 'Notion integration auth web token'
    required: true
  notion-database-id:
    description: 'ID of the Notion database to fetch blog posts from'
    required: true
  relative-date:
    description: 'Int as string to determine the numbers of days of posts to fetch from Notion'
    required: true
  site-url:
    description: 'Website URL, including protocol. Used to generate the `permalink` front matter'
    required: true
  site-baseurl:
    description: 'Website base URL. Used to generate the `permalink` front matter'
    required: false
  jekyll-root:
    description: 'Root directory of the Jekyll website. Do not set if root coincides with the git repo root'
    required: false
  publish-to-posts:
    description: 'If "true" converted pages should be published to _posts. Otherwise saves to _drafts.'
    required: false
  dry-run:
    description: 'If "true" runs in dry-run mode'
    required: false
  debuginfo:
    description: 'If non null, prints debug info'
    required: false
runs:
  using: 'docker'
  image: 'action.dockerfile'
  env:
    NOTION_TOKEN: ${{ inputs.notion-token }}
    NOTION_DATABASE_ID: ${{ inputs.notion-database-id }}
    RELATIVE_DATE: ${{ inputs.relative-date }}
    SITE_URL: ${{ inputs.site-url }}
    SITE_BASEURL: ${{ inputs.site-baseurl }}
    # set JEKYLL_ROOT to make it a relative path for user input
    # workspace is mounted to /github/workspace by GitHub Action.
    # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#accessing-files-created-by-a-container-action
    JEKYLL_ROOT: ${{ github.workspace }}/${{ inputs.jekyll-root }}
    PUBLISH_TO_POSTS: ${{ inputs.publish-to-posts }}
    DRY_RUN: ${{ inputs.dry-run }}
    DEBUG_INFO: ${{ inputs.debuginfo }}
